[package]
name = "deldup"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Program to delete or find duplicates"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
